export const iconList: any[] = [
  {
    name: '7부바지',
    class: 'clothesItem__cloth clothesItem__seven-piece-pants',
  },
  { name: '긴바지', class: 'clothesItem__cloth clothesItem__long-pants' },
  { name: '니트', class: 'clothesItem__cloth clothesItem__neat' },
  { name: '두꺼운코트', class: 'clothesItem__cloth clothesItem__thick-coat' },
  { name: '린넨옷', class: 'clothesItem__cloth clothesItem__linen' },
  { name: '목도리', class: 'clothesItem__cloth clothesItem__muffler' },
  { name: '민소매', class: 'clothesItem__cloth clothesItem__sleeveless' },
  { name: '바람막이', class: 'clothesItem__cloth clothesItem__wind-breaker' },
  { name: '반바지', class: 'clothesItem__cloth clothesItem__shorts' },
  { name: '반팔', class: 'clothesItem__cloth clothesItem__short-sleeve' },
  { name: '발열내의', class: 'clothesItem__cloth clothesItem__within-a-fever' },
  { name: '블라우스', class: 'clothesItem__cloth clothesItem__blouse' },
  { name: '셔츠', class: 'clothesItem__cloth clothesItem__shirts' },
  { name: '얇은재킷', class: 'clothesItem__cloth clothesItem__thin-jacket' },
  { name: '원피스', class: 'clothesItem__cloth clothesItem__one-piece' },
  { name: '장갑', class: 'clothesItem__cloth clothesItem__glove' },
  { name: '재킷', class: 'clothesItem__cloth clothesItem__jacket' },
  { name: '짧은치마', class: 'clothesItem__cloth clothesItem__short-skirt' },
  { name: '청바지', class: 'clothesItem__cloth clothesItem__jean' },
  { name: '청자켓', class: 'clothesItem__cloth clothesItem__denim-jacket' },
  {
    name: '캐시미어코트',
    class: 'clothesItem__cloth clothesItem__cashmere-coat',
  },
  { name: '트렌치코트', class: 'clothesItem__cloth clothesItem__trench-coat' },
  { name: '패딩', class: 'clothesItem__cloth clothesItem__padding' },
  { name: '항공점퍼', class: 'clothesItem__cloth clothesItem__ait-jacket' },
  { name: '후드', class: 'clothesItem__cloth clothesItem__hood' },
];
